---
title: "Resume"
---

View the PDF version [here](files/Ryan_Badzgon_Resume.pdf).

---

<h3>Ryan J. Badzgon</h3>

Project Management, Process Improvement, and Production Engineering professional with over 5 years of progressive experience. Successful in directing cross-functional teams and leading the execution of key strategic and operational projects and programs. Extensive experience with data analysis and reporting, performance management, budget management, and business planning. Proven success in utilizing Lean Six Sigma principles to optimize production, operations, and logistics across multiple sites and states, leading to multi-million-dollar cost savings. Earned Bachelor’s in Chemical Engineering, and currently pursuing PMP.


* Project and Program Management
* Operations Management
* Continuous Improvement and Optimization
* Budget Management
* Quality and Risk Management
* Data Analysis, Modeling, and Reporting
* Team Leadership and Training
* Vendor Relations
* Financial and Economic Analysis
* PMBOK, Agile, and Lean Six Sigma

---

<h3>Professional Experience</h3>

**Project Manager**  
**EQT Corporation, Canonsburg, PA	(2018 – Present)**  
  
* Project manager and continuous improvement leader for nation’s largest producer of natural gas; spearhead the redesign of various internal programs including compliance, sound mitigation, data analysis, and technology solutions, and oversee operations to support these new initiatives.
* Developed and lead Compliance Program comprising of over 300 weekly inspections across 3 states, utilized Smartsheet work management software to streamline and automate compliance operations, and trained team of 5 specialists, 18 inspectors, and 10 vendors on new processes; new program improved compliance company-wide while creating over $1.3M in cost savings and reducing needed FTE’s by 66%.
* Manage optimization of the Sound Mitigation Program consisting of 20 active projects, established program’s first budgets, SOPs, bid criteria, and communications, implemented new SQL database to house and analyze all assessment data, and oversee $3M annual budget and operations; program improvements are leading to over $840K in annual savings.
* Oversaw development of various data analytics solutions, implemented new Smartsheet modules department-wide with redesigned processes and enhanced cost management for $170M operation, established new daily reporting for each employee, and developed automated scheduling and communications with vendors; improved budget accuracy while minimizing processing times, and launched live dashboards for executives using Tibco Spotfire.
* Promoted from Senior Team Leader due to proven ability to lead complex and large projects, streamline operations, and effectively lead cross-functional personnel.

**Senior Team Leader, Operational Process Improvement**   
**EQT Corporation, Pittsburgh, PA	(2017 – 2018)**  
  
* Led waste management program for 14 sites and supervised team of 3 Operational Process Improvement personnel in multiple special field and operational projects; assigned tasks, provided advanced trainings and support, led performance management, and cultivated collaborative environment; mentorship helped 3 team members obtain significant promotions within the department.
* Directed $30M annual budget with 80 contractors, developed bid and award packages, outlined project scheduling, procedures, and costs, and oversaw contractor performance; ensured successful, efficient, and safe daily operations while minimizing costs and maximizing investment impact.  
* Partnered with company stakeholders to develop new SOP’s for each site; standardized personnel responsibilities, equipment layout, workflows, and KPI’s; new procedures, improved operations management, and team buy-in led to $3.5M in savings annually. 
* Streamlined waste management and disposal processes, developed standardized bid and vendor expectations across all sites, and oversaw awarding of new contracts; new procurement strategy is still used today and secures $2.5M in annual savings.
* Led team in implementing new solidification solutions, introducing new chemical addition processes, testing various advanced waste processing operations, and proposing new improvements to company leadership; new improvements led to over $1.5M in annual cost savings.
* Developed new executive dashboard in Spotfire to communicate the performance of each site and related contractors, outlined top budget and operational KPI’s, and customized reporting for various department personnel; transparency and accuracy enabled team to improve KPIs, secure multi-million-dollar cost reductions, and enhance safety.
  
**Process Engineer**  
**EQT Corporation, Pittsburgh, PA	(2015 – 2016)**  
  
* Led analysis and optimization of operational performance and costs for 140 sites with $240M annual budget; provided engineering, procurement, modeling, and data analysis support and expertise.  
* Spearheaded new natural gas fueling trailer initiative; established project scheduling, operational best practices, and communications, led team of field specialists and contractors, and secured partnerships with key vendors; improved utilization 30% year-over-year providing $3M in annual savings.
* Redesigned contractor performance operations, collected monthly performance and cost data, developed 5 new data analysis and performance dashboards, and distributed reports to department monthly; kept team and contractors up to date on project and individual performance resulting in cost and productivity improvements department-wide. 
* Analyzed over 30 bid proposals for various site operations, developed Excel models for each operation to standardize evaluation of each bid, and provided best recommendations; new tools helped ensure upper management was able to make the best possible decisions when awarding long-term operations contracts
* Evaluated economic impact of updates to well design, analyzed equipment, material, and labor costs, and developed model to determine long-term outcomes; concluded new design could reduce overall operational costs by $1.2M per site. 
* Developed multiple advanced “well economics” models, utilized by department to evaluate expected “well development costs” based on variable drilling parameter inputs; led to improved accuracy in forecasting expected costs. 
  
**Production Engineer**  
**EQT Corporation, Charleston, WV	(2014 – 2015)**  
  
* Directly assisted Regional Manager, developed $4M operation and capital budgets, contributed to planning, development, and execution of 80 capital projects; prepared cost estimates, analyses, and budgeting for projects, and provided ad-hoc operations and engineering support.  
  
**Facilities Engineering Intern**  
**Range Resources, Canonsburg, PA	(2013)** 
  
* Analyzed and recommended implementation of an asset relocation project with potential $2.5M annual savings, developed best practices guidebook for the Facilities Engineering Team, and supported day-to-day production and facilities operations.  

---
  
<h3>Education, Certifications, and Training</h3>

**Bachelor of Science in Chemical Engineering, Minor in Petroleum Engineering**  				
**University of Pittsburgh (2014)**  
  
* 3.67 GPA 
* Courses included: Engineering Analysis, Engineering Computing, Chemical Engineering Thermodynamics, Reactive Process Engineering, System Engineering, Dynamics and Modeling, and Process Design

**PMP Certification (expected 4/2019)**

**Data Scientist R Certification (expected 5/2019)**

**Lean Six Sigma Training (2018)**

**Professional Memberships**

* Society of Petroleum Engineers
* Project Management Institute (PMI)

**Technology Skills**

* Smartsheet
* Tibco Spotfire, Tableau, BI
* Excel, Macros
* Microsoft Office Package, Visio
* Salesforce
* R, Python
* Relational Databases
* SQL
* Alteryx
* AutoCAD

---